### PR TITLE
Update serialport.coffee

### PR DESCRIPTION
**Pull request by bertreb**
fix

### CODE REVIEW

**Comment by sweebee** [comment]
I'm not using pimatic anymore but what does this merge request fixes? Does this plugin not work anymore?

**Comment by bertreb** [comment]
Hi, this merge fixes the 's' missing in the Serialport.parser.Readline.  It should be Serialport.parsers.Readline. 
I asked M.Wittig to make me contributer for MySensor, so I can merge and publish a new version.

**Comment by sweebee** [comment]
I released a new version

**Comment by mwittig** [comment]
@sweebee thanks for sorting this! @bertreb I can't grant contributor for this project. Only the owner can do this

**Pull request merged**
