### PR TITLE
Added extra options

### PR DESCRIPTION
**Pull request by sweebee**

### CODE REVIEW

**Comment by sweebee** [comment]
Can/will you add this request?

**Comment by DheerajKhajuria** [comment]
@sweebee  can you use button sensor to detect open/close state. and will remain in updated state since we don't have reset timer there.

**Comment by sweebee** [comment]
Found an other way, just used the mysensorspir and my pir sends a false signal after 60 seconds. i have set the mysensorspir to 120 seconds.

But could you still add the extensions? So people can change the name (label) of opened/closed to something like away/home or something.

**Comment by DheerajKhajuria** [comment]
i think there's an option to override the label from opened/closed . let me check will revert back.

**Comment by sweebee** [comment]
Yes there is an option to override it, but its only possible if you add the extensions like for a button: ["xConfirm", "xLink", "xClosedLabel", "xOpenedLabel"]

**Comment by DheerajKhajuria** [comment]
@sweebee  ok kindly recommit the code with required changes. Also, let me know if i commit the dimmer device code.

**Comment by sweebee** [comment]
Recommited, with dimmer and extensions: https://github.com/DheerajKhajuria/pimatic-mysensors/pull/9

**Comment by DheerajKhajuria** [comment]
merged

**Pull request closed without merging**
